# Numpy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4,5,6], [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.linspace(0,5,77)

array([0.        , 0.06578947, 0.13157895, 0.19736842, 0.26315789,
       0.32894737, 0.39473684, 0.46052632, 0.52631579, 0.59210526,
       0.65789474, 0.72368421, 0.78947368, 0.85526316, 0.92105263,
       0.98684211, 1.05263158, 1.11842105, 1.18421053, 1.25      ,
       1.31578947, 1.38157895, 1.44736842, 1.51315789, 1.57894737,
       1.64473684, 1.71052632, 1.77631579, 1.84210526, 1.90789474,
       1.97368421, 2.03947368, 2.10526316, 2.17105263, 2.23684211,
       2.30263158, 2.36842105, 2.43421053, 2.5       , 2.56578947,
       2.63157895, 2.69736842, 2.76315789, 2.82894737, 2.89473684,
       2.96052632, 3.02631579, 3.09210526, 3.15789474, 3.22368421,
       3.28947368, 3.35526316, 3.42105263, 3.48684211, 3.55263158,
       3.61842105, 3.68421053, 3.75      , 3.81578947, 3.88157895,
       3.94736842, 4.01315789, 4.07894737, 4.14473684, 4.21052632,
       4.27631579, 4.34210526, 4.40789474, 4.47368421, 4.53947368,
       4.60526316, 4.67105263, 4.73684211, 4.80263158, 4.86842

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.51034178, 0.18540612, 0.28349372, 0.42801922, 0.71112348])

In [20]:
np.random.rand(5,5)

array([[0.2399287 , 0.22391431, 0.43366637, 0.37534319, 0.77140926],
       [0.55487605, 0.69316244, 0.92804811, 0.87993461, 0.17547943],
       [0.95515586, 0.45159828, 0.48864511, 0.81665456, 0.36218839],
       [0.71069065, 0.78137103, 0.35016499, 0.28341009, 0.77689516],
       [0.72409049, 0.7994827 , 0.33072147, 0.82032709, 0.49265193]])

In [21]:
np.random.randn(5)

array([-0.00588461, -0.15095077, -1.6065782 ,  0.82358734, -0.91612392])

In [22]:
np.random.randn(5,5)

array([[-0.18293542,  0.79700144,  0.42183087,  0.6458706 ,  0.67715621],
       [ 0.69993278,  0.936802  ,  1.00440204, -0.34653344, -1.41137296],
       [-1.26119209, -0.56195973,  0.76954595,  1.41486208,  0.34891724],
       [ 1.91029019,  0.51577479, -0.81128209,  1.43474687, -0.45431536],
       [-0.75027815, -0.68789009,  0.22587737, -2.48682653,  1.37112974]])

In [25]:
np.random.randint(1,100,10)

array([22, 10, 28, 95, 62, 18, 51, 31, 44, 45])

In [26]:
arr = np.arange(25)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr

array([40, 16, 17, 43, 43, 31, 23, 15,  9, 18])

In [32]:
ranarr.max()

43

In [33]:
ranarr.argmax()

3

In [34]:
ranarr.min()

9

In [35]:
ranarr.argmin()

8

In [37]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int64')