# NumPy Indexing and Selection

Array indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] = 100

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
sliceArr = arr[:5]

In [14]:
sliceArr

array([0, 1, 2, 3, 4])

In [15]:
sliceArr[:] = 100

In [16]:
sliceArr

array([100, 100, 100, 100, 100])

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
copyArr = arr.copy()

In [19]:
copyArr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [21]:
copyArr[:5] = 77

In [22]:
copyArr

array([77, 77, 77, 77, 77,  5,  6,  7,  8,  9, 10])

In [23]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Matrix Indexing

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[0][0] # double bracket indexing

5

In [27]:
arr_2d[2,1] # single bracket indexing

40

In [28]:
slice_arr_2d = arr_2d[:2,1:]

In [29]:
slice_arr_2d

array([[10, 15],
       [25, 30]])

In [50]:
slice_arr_2d = arr_2d[:,1:2]

In [51]:
slice_arr_2d.shape

(3, 1)

In [52]:
slice_arr_2d

array([[10],
       [25],
       [40]])

In [53]:
slice_arr_2d = arr_2d[:,1]

In [54]:
slice_arr_2d.shape

(3,)

In [55]:
slice_arr_2d

array([10, 25, 40])

Conditional Selection

In [56]:
arr = np.arange(1,11)

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
bool_arr = arr > 5

In [60]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [62]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])